// SPDX-License-Identifier: MIT
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.test.jsonc --include-runtime=false --strict-vars=false` (hash: 99c3abe123bc757b6498c0505c0a36ee)
interface __BaseEnv_Env {
	DB: D1Database;
	RECEIPT_RATE_LIMITER: RateLimit;
	ALLOWED_ORIGINS: string;
	AUDIT_BEARER_TOKEN: string;
	RETENTION_DAYS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "AUDIT_BEARER_TOKEN" | "RETENTION_DAYS">> {}
}
